const UNIQUE_VIOLATION_CODE = '23505';
const FOREIGN_KEY_VIOLATION_CODE = '23503';
const NOT_NULL_VIOLATION_CODE = '23502';
const CHECK_VIOLATION_CODE = '23514';
const NOT_ENUM_VALUE = '22P02';



module.exports = {
  UNIQUE_VIOLATION_CODE,
  FOREIGN_KEY_VIOLATION_CODE,
  NOT_NULL_VIOLATION_CODE,
  CHECK_VIOLATION_CODE,
  NOT_ENUM_VALUE
}